// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");
var Config$AgdaModeVscode = require("../Config.bs.js");
var Connection$AgdaModeVscode = require("./Connection.bs.js");

var instance = {
  connection: undefined,
  connecting: undefined,
  pendingRequest: undefined,
  spawnCount: 0
};

async function disconnect(log) {
  instance.pendingRequest = undefined;
  instance.connecting = undefined;
  var conn = instance.connection;
  if (conn === undefined) {
    return ;
  }
  instance.connection = undefined;
  try {
    await Connection$AgdaModeVscode.destroy(conn, log);
  }
  catch (exn){
    
  }
}

function schedule(task) {
  var p = instance.pendingRequest;
  var prev = p !== undefined ? Caml_option.valFromOption(p) : Promise.resolve({
          TAG: "Ok",
          _0: undefined
        });
  var next = async function () {
    try {
      await prev;
    }
    catch (exn){
      
    }
    return await task();
  };
  var promise = next();
  instance.pendingRequest = Caml_option.some(promise);
  return promise;
}

async function acquire(state) {
  var conn = instance.connection;
  if (conn !== undefined) {
    return {
            TAG: "Ok",
            _0: conn
          };
  }
  var promise = instance.connecting;
  if (promise !== undefined) {
    return await Caml_option.valFromOption(promise);
  }
  var promise$1 = Connection$AgdaModeVscode.makeWithFallback(state.platformDeps, state.memento, state.globalStorageUri, Config$AgdaModeVscode.Connection.getAgdaPaths(), [
        "als",
        "agda"
      ], state.channels.log);
  instance.connecting = Caml_option.some(promise$1);
  var result = await promise$1;
  instance.connecting = undefined;
  if (result.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: result._0
          };
  }
  var conn$1 = result._0;
  instance.spawnCount = instance.spawnCount + 1 | 0;
  instance.connection = conn$1;
  return {
          TAG: "Ok",
          _0: conn$1
        };
}

function getAgdaVersion() {
  var match = instance.connection;
  if (match === undefined) {
    return ;
  }
  if (match.TAG === "Agda") {
    return match._2;
  }
  var match$1 = match._2;
  if (match$1 !== undefined) {
    return match$1[1];
  }
  
}

async function switchConnection(state, path) {
  await disconnect(state.channels.log);
  var conn = await Connection$AgdaModeVscode.make(path);
  if (conn.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Establish",
              _0: conn._0
            }
          };
  }
  var conn$1 = conn._0;
  instance.spawnCount = instance.spawnCount + 1 | 0;
  instance.connection = conn$1;
  return {
          TAG: "Ok",
          _0: conn$1
        };
}

function getConnection() {
  return instance.connection;
}

function getSpawnCount() {
  return instance.spawnCount;
}

function resetSpawnCount() {
  instance.spawnCount = 0;
}

var $$Error;

exports.$$Error = $$Error;
exports.instance = instance;
exports.disconnect = disconnect;
exports.schedule = schedule;
exports.acquire = acquire;
exports.getAgdaVersion = getAgdaVersion;
exports.switchConnection = switchConnection;
exports.getConnection = getConnection;
exports.getSpawnCount = getSpawnCount;
exports.resetSpawnCount = resetSpawnCount;
/* Config-AgdaModeVscode Not a pure module */
