// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Chan$AgdaModeVscode = require("../Util/Chan.bs.js");
var Connection$AgdaModeVscode = require("../Connection/Connection.bs.js");
var State__View$AgdaModeVscode = require("./State__View.bs.js");
var Connection__Manager$AgdaModeVscode = require("../Connection/Connection__Manager.bs.js");

async function sendRequest(state, handleResponse, request) {
  var sendRequestAndHandleResponses = async function (connection, state, request, handler) {
    var onResponse = async function (response) {
      await handler(response);
      return Chan$AgdaModeVscode.emit(state.channels.log, {
                  TAG: "ResponseHandled",
                  _0: response
                });
    };
    Chan$AgdaModeVscode.emit(state.channels.log, {
          TAG: "RequestSent",
          _0: request
        });
    var error = await Connection$AgdaModeVscode.sendRequest(connection, state.document, request, onResponse);
    if (error.TAG === "Ok") {
      return await State__View$AgdaModeVscode.Panel.displayConnectionStatus(state, connection);
    } else {
      return await State__View$AgdaModeVscode.Panel.displayConnectionError(state, error._0);
    }
  };
  await Connection__Manager$AgdaModeVscode.schedule(async function () {
        var error = await Connection__Manager$AgdaModeVscode.acquire(state);
        if (error.TAG === "Ok") {
          await sendRequestAndHandleResponses(error._0, state, request, handleResponse);
          return {
                  TAG: "Ok",
                  _0: undefined
                };
        }
        var error$1 = error._0;
        await State__View$AgdaModeVscode.Panel.displayConnectionError(state, error$1);
        return {
                TAG: "Error",
                _0: error$1
              };
      });
}

async function sendRequestAndCollectResponses(state, request) {
  var responses = {
    contents: []
  };
  var responseHandler = async function (response) {
    responses.contents.push(response);
  };
  await sendRequest(state, responseHandler, request);
  return responses.contents;
}

exports.sendRequest = sendRequest;
exports.sendRequestAndCollectResponses = sendRequestAndCollectResponses;
/* Chan-AgdaModeVscode Not a pure module */
