// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var Vscode = require("vscode");
var PervasivesU = require("rescript/lib/js/pervasivesU.js");
var Chan$AgdaModeVscode = require("../../src/Util/Chan.bs.js");
var Mock$AgdaModeVscode = require("../../src/Main/Mock.bs.js");
var State$AgdaModeVscode = require("../../src/State/State.bs.js");
var Config$AgdaModeVscode = require("../../src/Config.bs.js");
var Memento$AgdaModeVscode = require("../../src/Memento.bs.js");
var Test__Util$AgdaModeVscode = require("./Test__Util.bs.js");
var Connection__Error$AgdaModeVscode = require("../../src/Connection/Shared/Connection__Error.bs.js");
var Connection__Manager$AgdaModeVscode = require("../../src/Connection/Connection__Manager.bs.js");

function makeMockState() {
  var logChannel = Chan$AgdaModeVscode.make();
  var channels_inputMethod = Chan$AgdaModeVscode.make();
  var channels_responseHandled = Chan$AgdaModeVscode.make();
  var channels_commandHandled = Chan$AgdaModeVscode.make();
  var channels = {
    inputMethod: channels_inputMethod,
    responseHandled: channels_responseHandled,
    commandHandled: channels_commandHandled,
    log: logChannel
  };
  var mockPlatform = Mock$AgdaModeVscode.Platform.makeBasic();
  var mockEditor = {
    document: { fileName: "test.agda" }
  };
  var mockUri = Vscode.Uri.file("/test/path");
  var mockMemento = Memento$AgdaModeVscode.make(undefined);
  return State$AgdaModeVscode.make(mockPlatform, channels, mockUri, mockUri, mockMemento, mockEditor, undefined);
}

describe("Connection Manager Integration", (function () {
        this.timeout(10000);
        var agdaMockPath = {
          contents: ""
        };
        var agdaMockPath2 = {
          contents: ""
        };
        before(async function () {
              Config$AgdaModeVscode.inTestingMode.contents = true;
              agdaMockPath.contents = await Test__Util$AgdaModeVscode.Endpoint.Agda.mock("2.6.4", "agda-manager-test");
              agdaMockPath2.contents = await Test__Util$AgdaModeVscode.Endpoint.Agda.mock("2.7.0.1", "agda-manager-test-2");
              return await Config$AgdaModeVscode.Connection.setAgdaPaths(Chan$AgdaModeVscode.make(), [agdaMockPath.contents]);
            });
        beforeEach(async function () {
              return await Connection__Manager$AgdaModeVscode.disconnect(Chan$AgdaModeVscode.make());
            });
        after(async function () {
              if (agdaMockPath.contents !== "") {
                await Test__Util$AgdaModeVscode.Endpoint.Agda.destroy(agdaMockPath.contents);
              }
              if (agdaMockPath2.contents !== "") {
                await Test__Util$AgdaModeVscode.Endpoint.Agda.destroy(agdaMockPath2.contents);
              }
              return await Connection__Manager$AgdaModeVscode.disconnect(Chan$AgdaModeVscode.make());
            });
        it("should share the same connection across multiple states", (async function () {
                var state1 = makeMockState();
                var state2 = makeMockState();
                var conn1Result = await Connection__Manager$AgdaModeVscode.acquire(state1);
                var conn1;
                conn1 = conn1Result.TAG === "Ok" ? conn1Result._0 : PervasivesU.failwith("Failed to acquire connection 1: " + Connection__Error$AgdaModeVscode.toString(conn1Result._0)[0]);
                var conn2Result = await Connection__Manager$AgdaModeVscode.acquire(state2);
                var conn2;
                conn2 = conn2Result.TAG === "Ok" ? conn2Result._0 : PervasivesU.failwith("Failed to acquire connection 2: " + Connection__Error$AgdaModeVscode.toString(conn2Result._0)[0]);
                Curry._3(Assert.equal, conn1, conn2, undefined);
                if (conn1.TAG === "Agda") {
                  return Curry._3(Assert.equal, conn1._1, agdaMockPath.contents, undefined);
                } else {
                  return PervasivesU.failwith("Expected Agda connection");
                }
              }));
        it("should reconnect if explicitly disconnected", (async function () {
                var state = makeMockState();
                var conn1Result = await Connection__Manager$AgdaModeVscode.acquire(state);
                var conn1;
                conn1 = conn1Result.TAG === "Ok" ? conn1Result._0 : PervasivesU.failwith("fail");
                await Connection__Manager$AgdaModeVscode.disconnect(state.channels.log);
                var conn2Result = await Connection__Manager$AgdaModeVscode.acquire(state);
                var conn2;
                conn2 = conn2Result.TAG === "Ok" ? conn2Result._0 : PervasivesU.failwith("fail");
                return Curry._3(Assert.notEqual, conn1, conn2, undefined);
              }));
        it("should update global connection when switching versions", (async function () {
                var state = makeMockState();
                await Connection__Manager$AgdaModeVscode.acquire(state);
                var switchResult = await Connection__Manager$AgdaModeVscode.switchConnection(state, agdaMockPath2.contents);
                var newConn;
                newConn = switchResult.TAG === "Ok" ? switchResult._0 : PervasivesU.failwith("Failed to switch: " + Connection__Error$AgdaModeVscode.toString({
                              TAG: "Establish",
                              _0: switchResult._0
                            })[0]);
                var activeConn = Connection__Manager$AgdaModeVscode.getConnection();
                Curry._3(Assert.deepStrictEqual, newConn, activeConn, undefined);
                if (newConn.TAG === "Agda") {
                  Curry._3(Assert.equal, newConn._1, agdaMockPath2.contents, undefined);
                  Curry._3(Assert.equal, newConn._2, "2.7.0.1", undefined);
                } else {
                  PervasivesU.failwith("Expected Agda connection");
                }
                var state2 = makeMockState();
                var acquiredResult = await Connection__Manager$AgdaModeVscode.acquire(state2);
                if (acquiredResult.TAG === "Ok") {
                  return Curry._3(Assert.equal, acquiredResult._0, newConn, undefined);
                } else {
                  return PervasivesU.failwith("Failed to acquire new connection");
                }
              }));
      }));

exports.makeMockState = makeMockState;
/*  Not a pure module */
